theme: jekyll-theme-minimal
logo: Pictures/profile.JPG
title: Ernest Theo
description: My name is Ernest Theo. I recieved my BS in Mechanical Engineering from San Jose State University. I am currently a Test Engineer
